// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teamscop.Api.Data;

#nullable disable

namespace Teamscop.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809205058_AgentStatusFourState")]
    partial class AgentStatusFourState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Teamscop.Api.Data.AgentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("IdleSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SegmentStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WorkedSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("CompanyId", "OccurredAt");

                    b.HasIndex("UserId", "ClientEventId")
                        .IsUnique();

                    b.HasIndex("UserId", "OccurredAt");

                    b.HasIndex("UserId", "EventType", "OccurredAt");

                    b.ToTable("agent_events", (string)null);
                });

            modelBuilder.Entity("Teamscop.Api.Data.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BusinessTimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("UTC");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OrgStructureVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Guid>("TokenJti")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Teamscop.Api.Data.PolicemanAuthorityGrant", b =>
                {
                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("StaffUserId", "PackageId");

                    b.HasIndex("PackageId");

                    b.ToTable("policeman_authority_grants", (string)null);
                });

            modelBuilder.Entity("Teamscop.Api.Data.StaffTrackingConfigEntity", b =>
                {
                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("BrowserHistoryEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<long>("ConfigVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("ScreenshotEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ScreenshotPeriodSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ScreenshotQuality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("TimeTrackEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StaffUserId");

                    b.HasIndex("CompanyId");

                    b.ToTable("staff_tracking_configs", (string)null);
                });

            modelBuilder.Entity("Teamscop.Api.Data.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaderUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LeaderUserId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Teamscop.Api.Data.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TeamId", "StaffUserId");

                    b.HasIndex("StaffUserId")
                        .IsUnique();

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("Teamscop.Api.Data.UninstallTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TicketHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TicketHash")
                        .IsUnique();

                    b.ToTable("uninstall_tickets", (string)null);
                });

            modelBuilder.Entity("Teamscop.Api.Data.UsbSessionTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceInstanceId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("DeviceUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TicketHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeviceUserId");

                    b.HasIndex("TicketHash")
                        .IsUnique();

                    b.ToTable("usb_session_tickets", (string)null);
                });

            modelBuilder.Entity("Teamscop.Api.Data.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessTotpFailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("AccessTotpLastUsedStepUninstall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<long>("AccessTotpLastUsedStepUsb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTimeOffset?>("AccessTotpLockoutUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AgentStatus")
                        .HasColumnType("text");

                    b.Property<string>("AgentStatusReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AgentStatusSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AppDefectSinceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppServiceState")
                        .HasColumnType("text");

                    b.Property<long>("AuthorityVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsPoliceman")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastAppReportAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastCaptureReason")
                        .HasColumnType("text");

                    b.Property<string>("LastCaptureState")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMissingComponents")
                        .HasColumnType("text");

                    b.Property<bool?>("LastOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("PolicemanUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UninstalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeviceKey")
                        .IsUnique();

                    b.HasIndex("CompanyId", "IsPoliceman");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Teamscop.Api.Data.AgentEvent", b =>
                {
                    b.HasOne("Teamscop.Api.Data.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teamscop.Api.Data.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teamscop.Api.Data.PolicemanAuthorityGrant", b =>
                {
                    b.HasOne("Teamscop.Api.Data.UserAccount", "StaffUser")
                        .WithMany("AuthorityGrants")
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("Teamscop.Api.Data.StaffTrackingConfigEntity", b =>
                {
                    b.HasOne("Teamscop.Api.Data.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teamscop.Api.Data.UserAccount", "StaffUser")
                        .WithOne()
                        .HasForeignKey("Teamscop.Api.Data.StaffTrackingConfigEntity", "StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("Teamscop.Api.Data.Team", b =>
                {
                    b.HasOne("Teamscop.Api.Data.Company", "Company")
                        .WithMany("Teams")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teamscop.Api.Data.UserAccount", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("Teamscop.Api.Data.TeamMember", b =>
                {
                    b.HasOne("Teamscop.Api.Data.UserAccount", "StaffUser")
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teamscop.Api.Data.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Teamscop.Api.Data.UninstallTicket", b =>
                {
                    b.HasOne("Teamscop.Api.Data.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Teamscop.Api.Data.UsbSessionTicket", b =>
                {
                    b.HasOne("Teamscop.Api.Data.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teamscop.Api.Data.UserAccount", "DeviceUser")
                        .WithMany()
                        .HasForeignKey("DeviceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DeviceUser");
                });

            modelBuilder.Entity("Teamscop.Api.Data.UserAccount", b =>
                {
                    b.HasOne("Teamscop.Api.Data.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Teamscop.Api.Data.Company", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Teamscop.Api.Data.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Teamscop.Api.Data.UserAccount", b =>
                {
                    b.Navigation("AuthorityGrants");
                });
#pragma warning restore 612, 618
        }
    }
}
